name: autoarima_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.25.3
  - pandas=1.5.3
  - matplotlib=3.6.5
  - scikit-learn=1.1.5
  - statsmodels=0.14.0
  - pmdarima=2.0.1
  - tqdm=4.64.1
  - pip
  - pip:
    - pmdarima==2.0.1
